import { chromium, expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import { mkdir, writeFile } from 'node:fs/promises';
const base = 'http://127.0.0.1:8000';
const output = 'docs/evidence';
await mkdir(output, { recursive: true });
const report = { executedAt: new Date().toISOString(), base, checks: [], accessibility: [], errors: [] };
const browser = await chromium.launch();
let page;
async function check(name, action) { await action(); report.checks.push({ name, passed: true }); console.log('PASS', name); }
async function audit(name) {
 const result = await new AxeBuilder({ page }).withTags(['wcag2a','wcag2aa','wcag21aa','wcag22aa']).analyze();
 report.accessibility.push({ name, violations: result.violations.map(v => ({ id: v.id, impact: v.impact, description: v.description, nodes: v.nodes.map(n => ({ target: n.target, summary: n.failureSummary })) })) });
 if (result.violations.length) console.log('AXE', name, JSON.stringify(report.accessibility.at(-1)));
}
async function layout(name) { const sizes = await page.evaluate(() => ({ width: window.innerWidth, scroll: document.documentElement.scrollWidth })); expect(sizes.scroll).toBeLessThanOrEqual(sizes.width); report.checks.push({ name: name+' no page overflow', passed:true }); }
async function login(email) { await page.goto(base+'/login'); await page.getByLabel('Email', { exact: true }).fill(email); await page.getByLabel('Kata sandi', { exact: true }).fill('CourtBook123!'); await page.getByRole('button', { name:'Masuk', exact:false }).click(); await page.waitForURL(email.startsWith('admin') ? '**/admin' : '**/bookings'); }
const date = new Date(Date.now()+2*86400000).toLocaleDateString('en-CA',{timeZone:'Asia/Jakarta'});
try {
 const context = await browser.newContext({ viewport:{width:1440,height:1000}, locale:'id-ID', timezoneId:'Asia/Jakarta' }); page = await context.newPage();
 page.on('pageerror', e => report.errors.push(e.message));
 await check('Desktop home and keyboard skip link', async () => { await page.goto(base); await expect(page.getByRole('heading',{name:'Jadwal pasti. Main sepenuh hati.'})).toBeVisible(); await page.keyboard.press('Tab'); await expect(page.getByRole('link',{name:'Lewati ke konten'})).toBeFocused(); await page.screenshot({path:output+'/home-desktop.png',fullPage:true}); await layout('home desktop'); });
 await audit('home desktop');
 await check('Search no-results and accessible clear', async () => {await page.goto(base+'/courts?q=does-not-exist');await expect(page.getByRole('heading',{name:'Lapangan tidak ditemukan'})).toBeVisible();await page.getByRole('button',{name:'Hapus pencarian',exact:true}).click();await expect(page.getByRole('heading',{name:'Tennis Court A'})).toBeVisible();});
 await check('Login error preserves email and shows invalid state',async()=>{await page.goto(base+'/login');await page.getByLabel('Email',{exact:true}).fill('pelanggan@courtbook.test');await page.getByLabel('Kata sandi',{exact:true}).fill('wrong');await page.getByRole('button',{name:'Masuk',exact:false}).click();await expect(page.getByRole('alert')).toContainText('Email atau kata sandi tidak sesuai');await expect(page.getByLabel('Email',{exact:true})).toHaveValue('pelanggan@courtbook.test');await expect(page.getByLabel('Email',{exact:true})).toHaveAttribute('aria-invalid','true');});
 await audit('login validation');
 await check('Password show/hide', async()=>{const input=page.getByLabel('Kata sandi',{exact:true});await page.getByRole('button',{name:'Tampilkan kata sandi',exact:true}).click();await expect(input).toHaveAttribute('type','text');await page.getByRole('button',{name:'Sembunyikan kata sandi',exact:true}).click();await expect(input).toHaveAttribute('type','password');});
 await login('pelanggan@courtbook.test');
 await check('Customer schedule selection and calculated price', async()=>{await page.goto(base+'/courts/1?date='+date);await page.locator('[data-slot="15"]').check();await page.getByLabel('Lama bermain',{exact:true}).selectOption('2');await expect(page.locator('[data-price-total]')).toContainText('200.000');await expect(page.locator('[data-price-dp]')).toContainText('100.000');await expect(page.locator('[data-slot="15"]')).toBeChecked();await page.screenshot({path:output+'/schedule-desktop.png',fullPage:true});});
 await audit('schedule desktop');
 await check('Unconfigured checkout and safe cancellation keyboard dialog',async()=>{await page.getByRole('button',{name:'Lanjut: periksa pesanan'}).click();await page.waitForURL(/\/bookings\/\d+$/);await expect(page.getByText('Pembayaran Sandbox belum tersedia.',{exact:false})).toBeVisible();await audit('checkout desktop');await page.screenshot({path:output+'/checkout-desktop.png',fullPage:true});await page.getByText('Ingin membatalkan pesanan?',{exact:true}).click();await page.getByRole('button',{name:'Batalkan booking',exact:true}).click();await expect(page.getByRole('dialog')).toBeVisible();await expect(page.getByRole('button',{name:'Kembali',exact:true})).toBeFocused();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).not.toBeVisible();await expect(page.getByRole('button',{name:'Batalkan booking',exact:true})).toBeFocused();await page.getByRole('button',{name:'Batalkan booking',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Batalkan booking',exact:true}).click();await expect(page.getByText('Dibatalkan',{exact:true})).toBeVisible();});
 await check('Profile unsaved changes guard',async()=>{await page.goto(base+'/profile');await page.getByLabel('Nama lengkap').fill('Perubahan belum disimpan');await page.getByRole('link',{name:'Cari lapangan',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('Perubahan belum disimpan');await page.getByRole('dialog').getByRole('button',{name:'Kembali',exact:true}).click();await expect(page.getByLabel('Nama lengkap')).toHaveValue('Perubahan belum disimpan');await page.getByRole('link',{name:'Cari lapangan',exact:true}).click();await page.getByRole('button',{name:'Tinggalkan halaman',exact:true}).click();await page.waitForURL('**/courts');});
 await page.getByRole('button',{name:'Keluar',exact:true}).click();
 await login('admin@courtbook.test');
 await audit('admin dashboard desktop');
 await page.screenshot({path:output+'/admin-desktop.png',fullPage:true});
 const courtName = 'Lapangan Uji Browser '+Date.now();
 await check('Admin create/edit/delete full flow',async()=>{await page.goto(base+'/admin/courts/create');await page.getByLabel('Nama lapangan').fill(courtName);await page.getByLabel('Deskripsi',{exact:true}).fill('Fasilitas simulasi untuk pengujian browser.');await page.getByLabel('Fasilitas',{exact:true}).fill('Lampu, Parkir');await page.getByRole('button',{name:'Simpan lapangan'}).click();await page.waitForURL('**/admin/courts');const row=page.getByRole('row').filter({hasText:courtName});await row.getByRole('link',{name:'Edit',exact:true}).click();await page.getByLabel('Tarif per jam (rupiah)').fill('150000');await page.getByRole('button',{name:'Simpan lapangan'}).click();await page.waitForURL('**/admin/courts');await expect(row).toContainText('150.000');await row.getByRole('button',{name:'Hapus',exact:true}).click();await expect(page.getByRole('dialog')).toContainText(courtName);await page.getByRole('button',{name:'Hapus lapangan',exact:true}).click();await expect(page.getByRole('row').filter({hasText:courtName})).toHaveCount(0);});
 await check('Admin maintenance create and release',async()=>{await page.goto(base+'/admin/maintenance');await page.getByLabel('Lapangan',{exact:true}).selectOption('2');await page.getByLabel('Mulai WIB',{exact:true}).fill(date+'T12:00');await page.getByLabel('Selesai WIB',{exact:true}).fill(date+'T14:00');await page.getByLabel('Alasan maintenance').fill('Maintenance uji browser');await page.getByRole('button',{name:'Blok jadwal',exact:true}).click();await expect(page.getByRole('row').filter({hasText:'Maintenance uji browser'})).toBeVisible();await page.goto(base+'/courts/2?date='+date);await expect(page.locator('[data-slot="12"]')).toBeDisabled();await expect(page.locator('.time-choice').filter({has:page.locator('[data-slot="12"]')})).toContainText('Maintenance');await page.goto(base+'/admin/maintenance');await page.getByRole('row').filter({hasText:'Maintenance uji browser'}).getByRole('button',{name:'Lepas blok',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Lepas blok',exact:true}).click();await expect(page.getByRole('row').filter({hasText:'Maintenance uji browser'})).toHaveCount(0);});
 await check('Narrow viewport home schedule/admin no overflow',async()=>{await page.setViewportSize({width:390,height:844});await page.emulateMedia({reducedMotion:'reduce'});for(const [name,url] of [['home',base],['schedule',base+'/courts/1?date='+date],['admin',base+'/admin/courts']]){await page.goto(url);await layout(name+' mobile');await audit(name+' mobile');await page.screenshot({path:output+'/'+name+'-mobile.png',fullPage:true});}await page.getByRole('link',{name:'Pengaturan',exact:true}).click();await expect(page.getByLabel('DP untuk booking baru (%)')).toBeVisible();});
 await check('Native select keyboard and reduced motion/global scrollbar',async()=>{await page.goto(base+'/courts/1?date='+date);const select=page.getByLabel('Lama bermain',{exact:true});await select.focus();await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');await expect(select).toHaveValue('2');const styles=await page.evaluate(()=>({scroll:getComputedStyle(document.documentElement).scrollbarColor,transition:getComputedStyle(document.querySelector('.btn')).transitionDuration}));expect(styles.scroll).not.toBe('auto');expect(styles.transition).toBe('0s');});
 report.passed = report.errors.length===0 && report.accessibility.every(item=>item.violations.length===0);
} catch(error) {report.passed=false;report.failure=String(error);console.error(error);if(page)await page.screenshot({path:output+'/browser-failure.png',fullPage:true});}
finally {await browser.close();await writeFile(output+'/browser-report.json',JSON.stringify(report,null,2));}
console.log(JSON.stringify({passed:report.passed,checks:report.checks.length,axeScans:report.accessibility.length,errors:report.errors.length,failure:report.failure}));
if(!report.passed)process.exitCode=1;